parameters:
  - name: token
    type: string
  - name: repository
    default: "pypi"
  - name: pythonVersion
    type: string

jobs:
  - job: pypi
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - template: step--python-install.yml
        parameters:
          pythonVersion: $(pythonVersion)
      - script: make build
        displayName: "Build package"
      - script: make publish
        env:
          GIT_REF: $(Build.SourceBranch)
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ parameters.token }}
          TWINE_REPOSITORY: ${{ parameters.repository }}
        displayName: "Publish package"
