parameters:
  - name: pythonVersion
    type: string

jobs:
  - job: Docs
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - template: step--python-install.yml
        parameters:
          pythonVersion: ${{ parameters.pythonVersion }}
      - bash: scripts/docs build
        displayName: "Build docs"
