parameters:
  - name: pythonVersion
    type: string

jobs:
  - job: Check
    pool:
      vmImage: "ubuntu-18.04"
    steps:
      - template: step--python-install.yml
        parameters:
          pythonVersion: ${{ parameters.pythonVersion }}
      - bash: scripts/check
        displayName: "Run checks"
